name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: CMake generation
      run: cmake .
    - name: make
      run: make
    - name: CMake release
      run:  cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: make
      run: make
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: Run valgrind
      run: valgrind ./merlin